### ISSUE TITLE
Should the avatar be a little taller?

### ISSUE THREAD

**Issue by atomrab** [atomrab/virtualchers#58]
I know we had some problems with avatar size and getting through doors, but I think we should assume that the occupants were tall enough to see through the windows and also walk through the doors. Can we raise the FP perspective enough to see through the windows in the floor above 36, and also get through the doors from the street into room 28 and room 34?

**Comment by ghost** [comment]
Fixed. Please, have a look if it's enough

**Comment by atomrab** [comment]
This is a tricky one. Now the viewpoint is fine for the second floor of complex 3, but too tall for the second floor of complex 2. And there's the issue of stepping up, since you still have to hop up all the stairs.

I'm not sure how to deal with this. Raising the windows of the second floor of complex 2, or lowering the windows of the second floor of complex 3, seems like a lot of trouble, from what you've said. But right now it either seems like the windows are at your knees in complex 2, or that you're the size of a small child in complex 3. Have you ever read Alice in Wonderland?

Anyway, if it's a huge pain to raise the windows in 2 or lower the windows in 3, let's leave this alone until everything else is done.

**Comment by atomrab** [comment]
Raising the windows in complex 2 has fixed the perspective issue, at least. Still don't know what to do about the stairs, though.
